import fs from "node:fs";
import path from "node:path";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import AIShowcase, { type AIVideoItem } from "../components/AIShowcase";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "AI Cinema & Generative Video | TAC",
  description:
    "Explore cutting-edge generative AI video productions, synthetic motion design, and world-building created with TAC's AI creative pipeline.",
};

// Curated default AI video projects with cinematic imagery & video links
const DEFAULT_AI_VIDEOS: AIVideoItem[] = [
  {
    id: "runway-gen3-cybercity",
    src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80&auto=format&fit=crop",
    alt: "Cybernetic Neo-Tokyo neon streetscape generated by AI",
    title: "Chroma Metropia",
    subtitle: "Runway Gen-3 Alpha • 4K Motion",
    tool: "Runway Gen-3",
    category: "World Building",
    prompt: "Anamorphic 35mm cinematic footage of futuristic neon rain in neo-city, reflections on wet asphalt, photorealistic cinematic lighting",
    duration: "0:24",
    youtubeId: "5qap5aO4i9A", // Lofi / ambient aesthetic video or sample
  },
  {
    id: "sora-ocean-dream",
    src: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80&auto=format&fit=crop",
    alt: "Bioluminescent deep ocean fantasy generated by AI",
    title: "Abyssal Dreamscape",
    subtitle: "OpenAI Sora • Fluid Dynamics",
    tool: "OpenAI Sora",
    category: "Fluid Simulation",
    prompt: "Cinematic drone dive into glowing bioluminescent ocean depths, ethereal jellyfish creatures with golden veins, ultra-detailed underwater photography",
    duration: "0:30",
    youtubeId: "r2t0pE73v2Q",
  },
  {
    id: "luma-fluid-sculpture",
    src: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=1200&q=80&auto=format&fit=crop",
    alt: "Liquid chrome metallic sculpture morphing in space",
    title: "Mercury Synthesis",
    subtitle: "Luma Dream Machine • Kinetic Art",
    tool: "Luma Dream Machine",
    category: "Kinetic Motion",
    prompt: "Morphing molten gold and mercury sculpture spinning weightlessly in obsidian studio void, raytraced caustics and specular blooms",
    duration: "0:18",
    youtubeId: "jNQXAC9IVRw",
  },
  {
    id: "kling-character-cinematics",
    src: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&q=80&auto=format&fit=crop",
    alt: "Photorealistic character portrait with expressive lighting",
    title: "Neural Persona",
    subtitle: "Kling 1.5 • Character Performance",
    tool: "Kling AI",
    category: "Character Design",
    prompt: "Close-up 85mm portrait of a cybernetic nomad turning towards camera, subtle micro-expressions, golden hour cinematic backlight, film grain",
    duration: "0:22",
    youtubeId: "9bZkp7q19f0",
  },
  {
    id: "midjourney-cosmic-drift",
    src: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&q=80&auto=format&fit=crop",
    alt: "Deep space nebula journey with cosmic dust",
    title: "Solaris Nebula",
    subtitle: "Midjourney v6.1 + Kling Motion",
    tool: "Midjourney + Kling",
    category: "Cosmic Sci-Fi",
    prompt: "Hyper-detailed journey through golden solar flares and deep purple interstellar dust, cinematic slow pan, IMAX 70mm aesthetic",
    duration: "0:28",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "pika-mech-evolution",
    src: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&q=80&auto=format&fit=crop",
    alt: "Futuristic robotic mechanical unfolding",
    title: "Titan Assembly",
    subtitle: "Pika 2.0 • Mechanical Rigging",
    tool: "Pika Labs",
    category: "Mecha VFX",
    prompt: "Time-lapse transformation of complex titanium origami mecha suit assembling in futuristic hangar, dramatic rim lighting",
    duration: "0:16",
    youtubeId: "kJQP7kiw5Fk",
  },
  {
    id: "stable-video-nature",
    src: "https://images.unsplash.com/photo-1511497584788-87676104235f?w=1200&q=80&auto=format&fit=crop",
    alt: "Mystical mist shrouded forest with golden light rays",
    title: "Sylvan Reverie",
    subtitle: "Stable Video Diffusion • Atmosphere",
    tool: "Stable Video",
    category: "Atmospheric Nature",
    prompt: "Slow gliding camera through dense ancient redwood forest bathed in misty volumetric golden god rays, morning dew, ultra photorealistic",
    duration: "0:25",
    youtubeId: "fJ9rUzIMcZQ",
  },
];

function getLocalAIVideos(): AIVideoItem[] {
  const dir = path.join(process.cwd(), "public", "gallery", "ai");
  let files: string[] = [];
  try {
    files = fs.readdirSync(dir);
  } catch {
    return [];
  }

  // Find all video files
  const videoFiles = files.filter((f) => /\.(mp4|webm|mov)$/i.test(f));
  if (videoFiles.length === 0) return [];

  return videoFiles.map((file, idx) => {
    const baseName = file.replace(/\.(mp4|webm|mov)$/i, "");
    // Check if there is a matching poster image (baseName.jpg, baseName.png, etc.)
    const matchingPoster = files.find(
      (f) =>
        f.startsWith(baseName) &&
        /\.(jpg|jpeg|png|webp|avif)$/i.test(f)
    );

    const posterUrl = matchingPoster
      ? `/gallery/ai/${matchingPoster}`
      : "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&q=80&auto=format&fit=crop";

    const formattedTitle = baseName
      .replace(/[-_]/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());

    return {
      id: `local-ai-${idx}-${baseName}`,
      src: posterUrl,
      videoUrl: `/gallery/ai/${file}`,
      title: formattedTitle,
      subtitle: "Local Upload • AI Production",
      tool: "Custom AI",
      category: "Local Vault",
      duration: "Video",
    };
  });
}

export default function AIPage() {
  const localItems = getLocalAIVideos();
  // Prepend local uploads so creator's new uploads appear first!
  const items = localItems.length > 0 ? [...localItems, ...DEFAULT_AI_VIDEOS] : DEFAULT_AI_VIDEOS;

  return (
    <div className="flex h-screen flex-col bg-bg text-foreground overflow-hidden">
      <Navbar />
      <main className="relative flex flex-1 flex-col overflow-hidden">
        <AIShowcase items={items} />
      </main>
    </div>
  );
}
